
get http://localhost:8080/hello

###
get http://localhost:8080/world

###
get http://localhost:8080/akuankka/mikkihiiri

###
get http://localhost:8080/api/locations

###
get http://localhost:8080/api/locations/3

###
delete http://localhost:8080/api/locations

###
POST http://localhost:8080/api/locations
Content-Type: application/json

{ "latitude": 78, "longitude": 125  }

###
# PUT request to update a specific location by ID
PUT http://localhost:8080/api/locations/2
Content-Type: application/json

{
    "latitude": 80,
    "longitude": 130
}
###
PATCH http://localhost:8080/api/locations/4
Content-Type: application/json

{
    "latitude": 85
}